Добавлен модуль "капчи" новых пользователей чата + связные правки
Djaler/ZloyBot pull request #6
Opened 2018-09-01 19:23 UTC by Senpos

Когда **пользователь входит** в супергруппу - у него **отбираются все права** на отправку сообщений, о чём сообщается в ответном сообщении. В этом же сообщении присутствует **кнопка**, на которую может нажать только этот пользователь, после чего **все права возвращаются**.

**Моменты, которые вызывают вопросы**:
 - добавление нескольких пользователей сразу - не протестировано; редкий случай
 - возможен абуз системы: если пользователю были ограничены права на канале - он может выйти и зайти, после чего все ограничения будут сняты

Что такое **"связные правки"**
В боте уже был обработчик для `CallbackQuery`, который находится в модуле `block_stickerpack`.

Так как в боте срабатывают **все** хэндлеры (даже одинаковые) для каждого из модулей - обработчик `CallbackQuery` из этого модуля вызывался вместе с таким же обработчиком в `block_stickerpack`.

Было принято решение как-то разграничить эти хэндлеры, поэтому для каждой кнопки `InlineKeyboardButton` в параметр `data` помимо нужных данных передается имя модуля, в котором эта кнопка была создана. В обработчике `CallbackQuery` эти данные разбиваются и идет проверка модуля: если модуль из `data` совпал с модулем, где идет проверка - мы попали в нужный хэндер.

```python
...
# создание кнопки с "data", в которой имя модуля и нужная информация
InlineKeyboardButton(self._INLINE_BUTTON_TEXT, callback_data=f'{__name__}/{user.id}'
...
# разбор "data"
module, suspect_id = query.data.split('/')

# удостоверимся, что мы в нужном модуле
if module != __name__:
    return
...
```

Несмотря на некоторые спорные моменты - работает приемлемо.

2018-09-01 19:26 UTC, Senpos commented
**TODO:**
- [ ] Добавить возможность включать / выключать "капчу" для админов из чата
- [ ] Проверить / добавить возможность работы "капчи" при добавлении нескольких пользователей

2018-09-01 19:41 UTC, Djaler requested changes

2018-09-01 19:41 UTC, Djaler commented on modules/block_stickerpack.py
> +        module, pack_name = query.data.split('/')
Вот тут бы проверку какую-нибудь делать. Потому что чисто теоретически (если другой модуль записывает данные в другом виде), тут может и не быть данных в таком виде

2018-09-01 19:41 UTC, Djaler commented on modules/user_join_captcha.py
> +                          'Добро пожаловать. 👊'
Какой-то слишком добрый для злого бота :D

2018-09-01 19:41 UTC, Djaler commented on modules/user_join_captcha.py
> +        if user.id == self._admin_id:
Можно ещё пропускать тех, кто уже есть в базе пользователей

2018-09-01 19:44 UTC, Senpos commented on modules/block_stickerpack.py
> +        module, pack_name = query.data.split('/')
Это решение обязывает использовать такой формат для `data`. Либо так, либо менять подход.

Но поменять тут кое-что таки надо - разбивать стоит только один раз, чтобы не "зацепить" часть с данными, в которых могут содержаться слэши.

2018-09-01 19:49 UTC, Senpos commented on modules/user_join_captcha.py
> +        if user.id == self._admin_id:
А пользователь разве не попадает в базу сразу же после первого сообщения? `join` по факту тоже сообщение.

2018-09-01 19:49 UTC, Djaler commented on modules/block_stickerpack.py
> +        module, pack_name = query.data.split('/')
Ну тогда я бы вынес эту логику в отдельные две функции. Типа, create_callback_data и parse_callback_data

2018-09-01 19:55 UTC, Djaler commented on modules/user_join_captcha.py
> +        if user.id == self._admin_id:
Если я не ошибаюсь, то нет. Там вроде как фильтр по тексту стоит

2018-10-02 17:37 UTC, Senpos commented
- добавлена обработка нескольких добавления пользователей
- добавлены хелперы для обработки CallbackQuery из разных модулей
- добавлена возможность включать / выключать модуль из `.env` (чтобы модуль работал - должна быть установлена переменная `USER_JOIN_CAPTCHA_ENABLED`)

2018-10-02 19:36 UTC, merged